# Generated by Django 3.1.6 on 2021-02-11 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='day_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='day_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
