# Generated by Django 3.1.6 on 2021-02-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='ideal_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='ideal_weight',
            field=models.IntegerField(default=1),
        ),
    ]
