# Generated by Django 3.1.6 on 2021-02-12 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
