# Generated by Django 3.1.6 on 2021-02-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('current_height', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('ideal_weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('ideal_height', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('day_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_intake', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('calorie_burnt', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('heart_rate', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('hours_slept', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('day_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
